import type { Order } from "@/components/dashboard/orders/OrdersList";

export const orders: Order[] = [
    {
      id: "#CM9801",
      user: { name: "Natali Craig", avatar: "Natali Craig" },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
    },
    {
      id: "#CM9802",
      user: { name: "Kate Morrison", avatar: "Kate Morrison" },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
    },
    {
      id: "#CM9803",
      user: { name: "Drew Cano", avatar: "Drew Cano" },
      project: "Client Project",
      address: "Bagwell Avenue Ocala",
      date: "1 hour ago",
      status: "Pending",
    },
    {
      id: "#CM9804",
      user: { name: "Orlando Diggs", avatar: "Orlando Diggs" },
      project: "Admin Dashboard",
      address: "Washburn Baton Rouge",
      date: "Yesterday",
      status: "Approved",
    },
    {
      id: "#CM9805",
      user: { name: "Andi Lane", avatar: "Andi Lane" },
      project: "App Landing Page",
      address: "Nest Lane Olivette",
      date: "Feb 2, 2023",
      status: "Rejected",
    },
    // Duplicate for pagination demo
    {
      id: "#CM9806",
      user: { name: "Natali Craig", avatar: "Natali Craig" },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
    },
    {
      id: "#CM9807",
      user: { name: "Kate Morrison", avatar: "Kate Morrison" },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
    },
    {
      id: "#CM9808",
      user: { name: "Drew Cano", avatar: "Drew Cano" },
      project: "Client Project",
      address: "Bagwell Avenue Ocala",
      date: "1 hour ago",
      status: "Pending",
    },
    {
      id: "#CM9809",
      user: { name: "Orlando Diggs", avatar: "Orlando Diggs" },
      project: "Admin Dashboard",
      address: "Washburn Baton Rouge",
      date: "Yesterday",
      status: "Approved",
    },
    {
      id: "#CM9810",
      user: { name: "Andi Lane", avatar: "Andi Lane" },
      project: "App Landing Page",
      address: "Nest Lane Olivette",
      date: "Feb 2, 2023",
      status: "Rejected",
    },
    {
      id: "#CM9811",
      user: { name: "Natali Craig", avatar: "Natali Craig" },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
    },
    {
      id: "#CM9812",
      user: { name: "Kate Morrison", avatar: "Kate Morrison" },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
    },
    {
      id: "#CM9813",
      user: { name: "Drew Cano", avatar: "Drew Cano" },
      project: "Client Project",
      address: "Bagwell Avenue Ocala",
      date: "1 hour ago",
      status: "Pending",
    },
    {
      id: "#CM9814",
      user: { name: "Orlando Diggs", avatar: "Orlando Diggs" },
      project: "Admin Dashboard",
      address: "Washburn Baton Rouge",
      date: "Yesterday",
      status: "Approved",
    },
    {
      id: "#CM9815",
      user: { name: "Andi Lane", avatar: "Andi Lane" },
      project: "App Landing Page",
      address: "Nest Lane Olivette",
      date: "Feb 2, 2023",
      status: "Rejected",
    },
    {
      id: "#CM9816",
      user: { name: "Natali Craig", avatar: "Natali Craig" },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
    },
  ];